### ISSUE TITLE
Bug: Chuubot Crash on SIF

### ISSUE THREAD

**Issue by Ryxias** [Ryxias/chuuni#63]
Stack trace:

```
schoolido.lu call: /api/cards/?rarity=UR&japan_only=false&ordering=random&page_size=1&name=Watanabe+You&
/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:196
      return null !== message_text.match(this.regex);
                                  ^

TypeError: Cannot read property 'match' of undefined
    at ChuubotListenerRegexp.matches (/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:196:35)
    at listeners.forEach (/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:51:24)
    at Array.forEach (native)
    at RTMClient.Chuubot.rtm.on (/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:49:24)
    at RTMClient.emit (/home/ryxias/repos/react-hell/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/client.js:82:39)
    at RTMClient._handleWsMessageViaEventHandler (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/rtm/client.js:471:10)  
    at RTMClient.handleWsMessage (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/rtm/client.js:425:10)
    at WebSocket.wrapper (/home/ryxias/repos/react-hell/node_modules/lodash/lodash.js:4968:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/ryxias/repos/react-hell/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:371:5)
    at /home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/home/ryxias/repos/react-hell/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at Pipe.onread (net.js:568:26)


```

**Comment by Ryxias** [comment]
Happened again:

```
schoolido.lu call: /api/cards/?rarity=UR&japan_only=false&ordering=random&page_size=1&name=Kunikida+Hanamaru&




/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:196
      return null !== message_text.match(this.regex);
                                  ^

TypeError: Cannot read property 'match' of undefined
    at ChuubotListenerRegexp.matches (/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:196:35)
    at listeners.forEach (/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:51:24)
    at Array.forEach (native)
    at RTMClient.Chuubot.rtm.on (/home/ryxias/repos/react-hell/lib/SlackbotFramework.js:49:24)
    at RTMClient.emit (/home/ryxias/repos/react-hell/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/client.js:82:39)
    at RTMClient._handleWsMessageViaEventHandler (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/rtm/client.js:471:10)  
    at RTMClient.handleWsMessage (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/rtm/client.js:425:10)
    at WebSocket.wrapper (/home/ryxias/repos/react-hell/node_modules/lodash/lodash.js:4968:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/ryxias/repos/react-hell/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:371:5)
    at /home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/home/ryxias/repos/react-hell/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at Pipe.onread (net.js:568:26)

npm ERR! Linux 4.9.38-16.35.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "chuubot"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-hell@0.0.1 chuubot: `NODE_ENV=production nodemon server/chuubot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-hell@0.0.1 chuubot script 'NODE_ENV=production nodemon server/chuubot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-hell package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production nodemon server/chuubot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-hell
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-hell
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryxias/repos/react-hell/npm-debug.log

```

**Comment by Ryxias** [comment]
Fixed this a while back
